server:
  port: 8002

spring:
  application:
    name: api2
  datasource:
    url: jdbc:postgresql://localhost:5432/db_streamworx
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate.ddl-auto: create
    jpa.show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

json-placeholder-api:
  base-url: https://jsonplaceholder.typicode.com
  todos-uri: todos
  users-uri: users
  posts-uri: posts

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true